{% set name = "interpret-core" %}
{% set version = "0.2.5" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/interpretml/interpret.git
  git_rev: "v{{ version }}"

build:
  noarch: generic
  number: 0
  script: "build.bat && {{ PYTHON }} python/scripts/build-js-bundles.py && cd python/interpret-core && {{ PYTHON }} -m pip install . -vv"  # [win]
  script: "./build.sh && {{ PYTHON }} python/scripts/build-js-bundles.py && cd python/interpret-core && {{ PYTHON }} -m pip install . -vv"  # [not win]

requirements:
  build:
    - gcc  # [linux]
    - clang  # [osx]
    - vc  # [win]
    - nodejs
  host:
    - pip
    - python
  run:
    - python

  run_constrained:
    # Equiv. to required.
    - scikit-learn >=0.18.1
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - joblib >=0.11
    # Equiv. to extras.
    - ipython >=7.4.0
    - ipykernel >=5.1.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.25.5
    - dill >=0.2.5
    - dash >=1.0.0
    - dash-cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0

about:
  home: "https://github.com/interpretml/interpret"
  license: MIT
  license_family: MIT
  license_file:  LICENSE
  summary: "Fit interpretable models. Explain blackbox machine learning."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - interpretml
